services:
  - type: web
    name: n8n
    env: docker
    repo: https://github.com/HSTMSAP/0107n8n-mori
    branch: main
    dockerfilePath: ./Dockerfile
    startCommand: n8n start
    healthCheckPath: /
    envVars:
      - key: GENERIC_TIMEZONE
        value: Europe/Moscow
      - key: WEBHOOK_TUNNEL_URL
        value: https://n8n-1gmc.onrender.com
      - key: N8N_HOST
        value: n8n-1gmc.onrender.com
